// test_asset_manifest.cpp — invariants on the engine's mesh table (src/engine/asset_manifest.h).
//
// WHERE THIS SITS IN THE DEFENCE. `assets/meshes/*.obj` is gitignored: meshes are BUILT by
// tools/build_assets.py, never committed. The failure this guards against is a mesh named by the
// engine that the generator does not produce — it loads fine for the developer who generated the
// .obj by hand, and does not exist at all on CI or in any release build.
//
// The AUTHORITATIVE check for that lives in build_assets.py's verify_manifest(), because it can
// compare the table against the files the generator ACTUALLY WROTE this run. A stale .obj sitting
// in a working tree cannot fool it. This file cannot make that comparison — it can only see the
// filesystem, which is the very thing that masked the original bug — so it deliberately does NOT
// try to be the primary net.
//
// What it pins instead are the invariants that are pure C++ and that no Python check can see: a
// duplicate name silently shadows (name lookup returns the first match), a table that outgrows the
// registry silently drops its TAIL, and a malformed path fails to load with no other symptom.

#include <doctest/doctest.h>
#include "engine/asset_manifest.h"
#include <cstdio>
#include <cstring>
#include <string>

#ifndef DUNGEON_REPO_ROOT
#define DUNGEON_REPO_ROOT "."
#endif

namespace {

// Read a file's size; 0 (or missing) both mean "nothing usable here".
long fileSize(const std::string& path) {
    std::FILE* f = std::fopen(path.c_str(), "rb");
    if (!f) return -1;
    std::fseek(f, 0, SEEK_END);
    long n = std::ftell(f);
    std::fclose(f);
    return n;
}

std::string repoPath(const char* rel) {
    return std::string(DUNGEON_REPO_ROOT) + "/" + rel;
}

// True once the asset generator has been run at least once. A fresh clone has no meshes at all, and
// failing 100+ checks there would be noise rather than signal — the generator is what gates that.
bool assetsBuilt() {
    return fileSize(repoPath(kMeshAssets[0].path)) > 0;
}

} // namespace

TEST_CASE("AssetManifest: the mesh table fits the registry") {
    // The load loop BREAKS at capacity, so an overflow does not error — it silently drops every
    // entry past the cap, which is the tail of the table (today: the player class meshes). Slot 0 is
    // the built-in cube fallback, hence the +1. asset_manifest.h static_asserts this too; the test
    // states the consequence in a place a human reads.
    CHECK(kMeshAssetCount + 1 <= MESH_DEF_CAPACITY);
    CHECK(kMeshAssetCount > 0);
}

TEST_CASE("AssetManifest: no duplicate mesh names") {
    // Meshes are resolved BY NAME into an integer id once at startup. A duplicate name is not an
    // error anywhere: the second entry loads, occupies a registry slot, and is then unreachable
    // because every lookup returns the first match. The dead mesh is invisible until someone
    // wonders why their new variant never appears.
    for (u32 i = 0; i < kMeshAssetCount; i++) {
        for (u32 j = i + 1; j < kMeshAssetCount; j++) {
            INFO("duplicate mesh name: ", kMeshAssets[i].name);
            CHECK(std::strcmp(kMeshAssets[i].name, kMeshAssets[j].name) != 0);
        }
    }
}

TEST_CASE("AssetManifest: no duplicate mesh paths") {
    // Two names pointing at one .obj is legal but always a copy-paste slip — the second name gets
    // the first one's geometry, so the mesh you meant to add is simply never used.
    for (u32 i = 0; i < kMeshAssetCount; i++) {
        for (u32 j = i + 1; j < kMeshAssetCount; j++) {
            INFO("duplicate mesh path: ", kMeshAssets[i].path);
            CHECK(std::strcmp(kMeshAssets[i].path, kMeshAssets[j].path) != 0);
        }
    }
}

TEST_CASE("AssetManifest: every entry is well-formed") {
    for (u32 i = 0; i < kMeshAssetCount; i++) {
        const MeshAsset& m = kMeshAssets[i];
        REQUIRE(m.name != nullptr);
        REQUIRE(m.path != nullptr);
        CHECK(m.name[0] != '\0');

        // The generator writes into assets/meshes/ and the loader reads from there. A path that
        // strays outside it loads on the author's machine and nowhere else.
        INFO("path: ", m.path);
        CHECK(std::strncmp(m.path, "assets/meshes/", 14) == 0);

        const size_t len = std::strlen(m.path);
        REQUIRE(len > 4);
        CHECK(std::strcmp(m.path + len - 4, ".obj") == 0);
    }
}

TEST_CASE("AssetManifest: every named mesh exists on disk and holds geometry") {
    // Secondary net (see the file header): catches "never generated at all", which is the common
    // case in practice. It cannot catch "generated by hand but missing from build_assets.py" —
    // build_assets.py's verify_manifest() owns that, and is the check that runs in CI.
    if (!assetsBuilt()) {
        MESSAGE("assets/meshes is empty — run tools/build_assets.py. Skipping on-disk checks.");
        return;
    }

    for (u32 i = 0; i < kMeshAssetCount; i++) {
        INFO("mesh '", kMeshAssets[i].name, "' -> ", kMeshAssets[i].path);
        // A 0-byte .obj is what a crashed/interrupted generator leaves behind: it "exists", loads to
        // zero geometry, and renders as the fallback cube — the exact symptom we are hunting.
        CHECK(fileSize(repoPath(kMeshAssets[i].path)) > 0);
    }
}

TEST_CASE("AssetManifest: every decoration prop exists on disk") {
    if (!assetsBuilt()) return;

    for (u32 i = 0; i < kPropAssetCount; i++) {
        INFO("prop: ", kPropAssets[i].path);
        CHECK(fileSize(repoPath(kPropAssets[i].path)) > 0);
        CHECK(kPropAssets[i].material != nullptr);
        CHECK(kPropAssets[i].radius > 0.0f);
    }
}
