#!/usr/bin/env python3
"""Generate 16x16 item icon silhouettes as a C++ header of packed bitmasks.

The inventory item icons in src/renderer/item_icons.cpp are 16 rows of u16, where bit 15 is
the leftmost pixel (the `s_iconData` table). Most are still authored inline there; this tool
generates the icons we want produced FROM the asset pipeline — so CI/CD rebuilds them via
tools/build_assets.py instead of them living as hand-edited bitmaps — and emits each as an
`ITEM_ICON_<NAME>_ROWS` macro that the inline table splices into its array.

Output: src/renderer/item_icons_gen.h  (mirrors gen_skill_icons.py's generated-header pattern)
"""

import os

W = H = 16


def grid():
    return [[0] * W for _ in range(H)]


def px(g, x, y, v=1):
    if 0 <= x < W and 0 <= y < H:
        g[y][x] = v


def rect(g, x0, y0, x1, y1, v=1):
    for y in range(max(0, y0), min(H, y1 + 1)):
        for x in range(max(0, x0), min(W, x1 + 1)):
            g[y][x] = v


def ring(g, cx, cy, r_out, r_in, v=1):
    """Fill an annulus (ring with a hole) — r_in <= dist <= r_out."""
    for y in range(H):
        for x in range(W):
            d2 = (x - cx) ** 2 + (y - cy) ** 2
            if r_in * r_in <= d2 <= r_out * r_out:
                g[y][x] = v


def draw_gloves():
    """An OPEN-HAND glove: four separated fingers pointing up, a thumb out to the left, and a
    cuff at the wrist. The gaps between the fingers give a comb-like top edge that no blade has
    — the decisive feature that stops it reading like the cleaver (a solid wide-top taper)."""
    g = grid()
    # Four separated fingers (1px wide, 1px gaps at x=5,7,9) — the unmistakable "hand" tell
    for fx in (4, 6, 8, 10):
        rect(g, fx, 1, fx, 4)
    # Knuckles: fingers merge into the back of the hand
    rect(g, 4, 5, 10, 6)
    # Palm
    rect(g, 4, 6, 10, 9)
    # Thumb sticking out to the LEFT, clearly off the finger row
    rect(g, 1, 6, 3, 7)
    rect(g, 2, 8, 3, 8)
    # Wrist narrows
    rect(g, 5, 10, 9, 10)
    # Flared cuff band at the bottom + base trim
    rect(g, 3, 11, 11, 12)
    rect(g, 4, 13, 10, 13)
    return g


def draw_chakram():
    """A bladed throwing ring: a thick metal annulus (hole in the middle) with four sharp blade
    points at N/E/S/W. The central hole + outward spikes read clearly as a chakram and are
    distinct from the thin RING item-icon outline."""
    g = grid()
    cx = cy = 8
    # Thick ring body with an open center
    ring(g, cx, cy, 6.6, 3.4)
    # Four blade points jutting out past the rim (cardinal directions)
    rect(g, cx, 0, cx, 2)      # north
    rect(g, cx, 13, cx, 15)    # south
    rect(g, 0, cy, 2, cy)      # west
    rect(g, 13, cy, 15, cy)    # east
    # Small diagonal nubs for a serrated look
    for (dx, dy) in ((-1, -1), (1, -1), (-1, 1), (1, 1)):
        px(g, cx + dx * 6, cy + dy * 6)
    return g


def pack(g):
    """Pack a 16x16 boolean grid into 16 u16 rows (bit 15 = leftmost pixel)."""
    rows = []
    for y in range(H):
        bits = 0
        for x in range(W):
            if g[y][x]:
                bits |= 1 << (15 - x)
        rows.append(bits)
    return rows


def write_header(icons, path):
    with open(path, "w") as f:
        f.write("// Auto-generated by tools/gen_item_icons.py — do not edit manually.\n")
        f.write("// 16x16 item icon silhouettes, packed u16-per-row (bit 15 = leftmost pixel).\n")
        f.write("// Spliced into the s_iconData table in item_icons.cpp via ITEM_ICON_*_ROWS.\n")
        f.write("#pragma once\n\n")
        for name, rows in icons:
            vals = ", ".join(f"0x{v:04X}" for v in rows)
            f.write(f"#define ITEM_ICON_{name}_ROWS {vals}\n")
    print(f"Generated {len(icons)} item icon(s) to {path}")


def main():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_path = os.path.join(repo_root, "src", "renderer", "item_icons_gen.h")
    icons = [
        ("GLOVES", pack(draw_gloves())),
        ("CHAKRAM", pack(draw_chakram())),
    ]
    write_header(icons, out_path)


if __name__ == "__main__":
    main()
